# https://docs.microsoft.com/vsts/pipelines/languages/xamarin

jobs:
- job: Android
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    buildConfiguration: 'Debug'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  steps:
  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

  - task: VSBuild@1
    inputs:
      solution: '**/*Monshare.csproj'
      configuration: '$(buildConfiguration)'
      msbuildArchitecture: 'x64'

  - task: VSBuild@1
    inputs:
      solution: '**/*droid*.csproj'
      vsVersion: '15.0'
      msbuildArgs: '/t:SignAndroidPackage /p:Configuration=Debug'
      configuration: '$(buildConfiguration)'



  - task: CopyFiles@2
    inputs:
      Contents: '**/*Signed*.apk'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'apkapp'
      publishLocation: 'Container'

- job: iOS
  pool:
    vmImage: 'macOS-10.13'
  variables:
    buildConfiguration: 'Debug'
  steps:
  - task: NuGetToolInstaller@0
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'
  - task: XamariniOS@2
    inputs:
      solutionFile: '**/*iOS.csproj'
      configuration: '$(buildConfiguration)'
      buildForSimulator: true
      packageApp: false
  - task: CopyFiles@2
    inputs:
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      OverWrite: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'iosapp'
      publishLocation: 'Container'